from math import fabs
import time

import pydill as dill


class EventHandler:
    """Simple handler for events generated by DILL."""

    def __init__(self) -> None:
        self._known_device_guids = set([])

    def joystick_device_handler(
        self, summary: dill._DeviceSummary, action_c: int
    ) -> None:
        """Simple handler that just prints device information upon device change."""
        summary = dill.DeviceSummary(summary)
        action = dill.DeviceActionType(action_c)
        if summary.device_guid not in self._known_device_guids:
            self._known_device_guids.add(summary.device_guid)
            print(
                f"Device GUID=s{summary.device_guid}, Vendor ID={summary.vendor_id}, Name={summary.name}"
            )
            print(
                f"Device NumAxes={summary.axis_count}, NumButtons={summary.button_count}, NumHats={summary.hat_count}, Force Feedback={summary.force_feedback}"
            )
            for axis_i, axis_info in enumerate(summary.axis_map):
                print(
                    f"Axis {axis_i} LinearIndex={axis_info.linear_index}, AxisIndex={axis_info.axis_index}"
                )

    def joystick_event_handler(self, data: dill._JoystickInputData) -> None:
        """Simple handler that just prints any new joystick inputs."""
        event = dill.InputEvent(data)
        if event.input_type == dill.InputType.Axis:
            line = f"Device GUID={event.device_guid.uuid}, Axis={event.input_index}, value={event.value}"
        elif event.input_type == dill.InputType.Button:
            line = f"Device GUID={event.device_guid.uuid}, Button={event.input_index}, value={event.value} (0=released, 1=pressed)"
        elif event.input_type == dill.InputType.Hat:
            line = f"Device GUID={event.device_guid.uuid}, Hat={event.input_index}, value={event.value}"
        print(line)


def main():
    event_handler = EventHandler()
    dill.DILL.set_device_change_callback(event_handler.joystick_device_handler)
    dill.DILL.set_input_event_callback(event_handler.joystick_event_handler)
    dill.DILL.init()
    while True:
        time.sleep(1)
        if not dill.DILL.get_device_count():
            print("No devices yet, plug in a device.")


if __name__ == "__main__":
    main()
